"""add operation_definition_id to plan_demand_line

Revision ID: 01c0ce262567
Revises: 4f1c75b3ffaf
Create Date: 2026-07-12 16:42:34.324325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c0ce262567'
down_revision: Union[str, Sequence[str], None] = '4f1c75b3ffaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_demand_line', sa.Column('operation_definition_id', sa.String(length=36), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_demand_line', 'operation_definition_id')
    # ### end Alembic commands ###
