"""add overtime_dates to staff and equipment

Revision ID: 2351115095b5
Revises: 01c0ce262567
Create Date: 2026-07-12 17:32:11.010485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2351115095b5'
down_revision: Union[str, Sequence[str], None] = '01c0ce262567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('overtime_dates', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('staff', sa.Column('overtime_dates', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'overtime_dates')
    op.drop_column('equipment', 'overtime_dates')
    # ### end Alembic commands ###
