"""add staff qualifications and operation required_qualification

Revision ID: 2d71eedd0842
Revises: 54ef63bc8f57
Create Date: 2026-07-09 21:42:16.894576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d71eedd0842'
down_revision: Union[str, Sequence[str], None] = '54ef63bc8f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation_definition', sa.Column('required_qualification', sa.String(length=100), nullable=True))
    op.add_column('operation_instance', sa.Column('required_qualification', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('qualifications', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'qualifications')
    op.drop_column('operation_instance', 'required_qualification')
    op.drop_column('operation_definition', 'required_qualification')
    # ### end Alembic commands ###
