"""create assignment table

Revision ID: 36351f163a57
Revises: 785114aff846
Create Date: 2026-07-08 23:48:00.320434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36351f163a57'
down_revision: Union[str, Sequence[str], None] = '785114aff846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('plan_version_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=100), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('planned_start', sa.Integer(), nullable=False),
    sa.Column('planned_end', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_plan_version_id'), 'assignment', ['plan_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_plan_version_id'), table_name='assignment')
    op.drop_table('assignment')
    # ### end Alembic commands ###
