"""add equipment fv_duration and fv_validity

Revision ID: 3c5248455004
Revises: ff2b5745716a
Create Date: 2026-07-11 20:57:28.543956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5248455004'
down_revision: Union[str, Sequence[str], None] = 'ff2b5745716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'equipment',
        sa.Column('fv_duration', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'equipment',
        sa.Column('fv_validity', sa.Integer(), nullable=False, server_default='14'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'fv_validity')
    op.drop_column('equipment', 'fv_duration')
    # ### end Alembic commands ###
