"""rename staff/equipment availability to unavailable_dates

Revision ID: 4f1c75b3ffaf
Revises: 79e20307e699
Create Date: 2026-07-12 15:25:14.234824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4f1c75b3ffaf'
down_revision: Union[str, Sequence[str], None] = '79e20307e699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'equipment',
        sa.Column('unavailable_dates', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.drop_column('equipment', 'availability')
    op.add_column(
        'staff',
        sa.Column('unavailable_dates', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.drop_column('staff', 'availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('availability', sqlite.JSON(), nullable=False, server_default='[]'))
    op.drop_column('staff', 'unavailable_dates')
    op.add_column('equipment', sa.Column('availability', sqlite.JSON(), nullable=False, server_default='[]'))
    op.drop_column('equipment', 'unavailable_dates')
    # ### end Alembic commands ###
