"""add availability to equipment and staff

Revision ID: 54ef63bc8f57
Revises: f58ad6519f0b
Create Date: 2026-07-09 21:10:50.030991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ef63bc8f57'
down_revision: Union[str, Sequence[str], None] = 'f58ad6519f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('availability', sa.JSON(), nullable=False))
    op.add_column('staff', sa.Column('availability', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'availability')
    op.drop_column('equipment', 'availability')
    # ### end Alembic commands ###
