"""create equipment, staff, workflow_definition, operation_definition tables

Revision ID: 785114aff846
Revises: 0d33be28fc36
Create Date: 2026-07-08 22:39:16.323354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '785114aff846'
down_revision: Union[str, Sequence[str], None] = '0d33be28fc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=False)
    op.create_table('staff',
    sa.Column('staff_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_staff_code'), 'staff', ['staff_code'], unique=False)
    op.create_table('workflow_definition',
    sa.Column('workflow_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definition_workflow_code'), 'workflow_definition', ['workflow_code'], unique=False)
    op.create_table('operation_definition',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('required_capability', sa.String(length=100), nullable=True),
    sa.Column('required_skill', sa.String(length=100), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_definition_workflow_id'), 'operation_definition', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_definition_workflow_id'), table_name='operation_definition')
    op.drop_table('operation_definition')
    op.drop_index(op.f('ix_workflow_definition_workflow_code'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    op.drop_index(op.f('ix_staff_staff_code'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
