"""create plan_demand_line table

Revision ID: 79e20307e699
Revises: dbfaa1c94b03
Create Date: 2026-07-12 14:37:00.086923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e20307e699'
down_revision: Union[str, Sequence[str], None] = 'dbfaa1c94b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_demand_line',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_definition_id', sa.String(length=36), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_demand_line_plan_id'), 'plan_demand_line', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_demand_line_plan_id'), table_name='plan_demand_line')
    op.drop_table('plan_demand_line')
    # ### end Alembic commands ###
