"""create workflow_instance, operation_instance, planning_context tables

Revision ID: 9ef789e4dd6e
Revises: 538266a8a99e
Create Date: 2026-07-09 20:11:24.677756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef789e4dd6e'
down_revision: Union[str, Sequence[str], None] = '538266a8a99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_context',
    sa.Column('plan_version_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_snapshot', sa.JSON(), nullable=False),
    sa.Column('staff_snapshot', sa.JSON(), nullable=False),
    sa.Column('solver_profile', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_context_plan_version_id'), 'planning_context', ['plan_version_id'], unique=True)
    op.create_table('workflow_instance',
    sa.Column('plan_version_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_definition_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instance_plan_version_id'), 'workflow_instance', ['plan_version_id'], unique=False)
    op.create_table('operation_instance',
    sa.Column('workflow_instance_id', sa.String(length=36), nullable=False),
    sa.Column('operation_definition_id', sa.String(length=36), nullable=False),
    sa.Column('operation_code', sa.String(length=100), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('duration_shift', sa.Integer(), nullable=False),
    sa.Column('required_capability', sa.String(length=100), nullable=True),
    sa.Column('required_skill', sa.String(length=100), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_instance_workflow_instance_id'), 'operation_instance', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_instance_workflow_instance_id'), table_name='operation_instance')
    op.drop_table('operation_instance')
    op.drop_index(op.f('ix_workflow_instance_plan_version_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index(op.f('ix_planning_context_plan_version_id'), table_name='planning_context')
    op.drop_table('planning_context')
    # ### end Alembic commands ###
