"""add assignment reason column

Revision ID: c71aa50e60f9
Revises: 36351f163a57
Create Date: 2026-07-08 23:58:32.475479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71aa50e60f9'
down_revision: Union[str, Sequence[str], None] = '36351f163a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'reason')
    # ### end Alembic commands ###
