"""add plan availability unavailable_dates

Revision ID: dbfaa1c94b03
Revises: 3c5248455004
Create Date: 2026-07-12 09:42:51.430376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfaa1c94b03'
down_revision: Union[str, Sequence[str], None] = '3c5248455004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'plan_resource_availability',
        sa.Column('unavailable_dates', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_resource_availability', 'unavailable_dates')
    # ### end Alembic commands ###
