"""create plan_resource_availability table

Revision ID: ff2b5745716a
Revises: e5061728a9bc
Create Date: 2026-07-11 20:05:02.049995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2b5745716a'
down_revision: Union[str, Sequence[str], None] = 'e5061728a9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_resource_availability',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('resource_kind', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'resource_kind', 'resource_id', name='uq_plan_resource')
    )
    op.create_index(op.f('ix_plan_resource_availability_plan_id'), 'plan_resource_availability', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_resource_availability_plan_id'), table_name='plan_resource_availability')
    op.drop_table('plan_resource_availability')
    # ### end Alembic commands ###
